{
 "title": "PowerStore LND1",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "volume_name",
    "label": "Volumes",
    "query": {
     "query": "label_values({job=~\"powerstore-prometheus-exporter\"},vol_name)"
    }
   },
   {
    "name": "fc_port_name",
    "label": "FC Ports",
    "query": {
     "query": "label_values({job=~\"powerstore-prometheus-exporter\"},fc_name)"
    }
   },
   {
    "name": "eth_port_name",
    "label": "Ethernet Ports",
    "query": {
     "query": "label_values({job=~\"powerstore-prometheus-exporter\"},eth_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Appliance IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "targets": [
    { "expr": "appliance_iops_read{}", "legendFormat": "Read" },
    { "expr": "appliance_iops_write{}", "legendFormat": "Write" },
    {
     "expr": "appliance_iops_read{} + appliance_iops_write{}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Physical Capacity in Use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cap_used{} * 100 / cap_total{}" }
   ]
  },
  {
   "title": "Appliance Bandwidth (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "appliance_bandwidth_read{} /1048576",
     "legendFormat": "Read "
    },
    {
     "expr": "appliance_bandwidth_write{} /1048576",
     "legendFormat": "Write"
    },
    {
     "expr": "(appliance_bandwidth_read{} + appliance_bandwidth_write{}) /1048576",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Data Reduction Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_reduction{}" }
   ]
  },
  {
   "title": "Physical Capacity Total (TB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cap_total{} / 1099511627776" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 20, "x": 0, "y": 12 }, "options": { "content": "# Volume Level Metrics" } },
  {
   "title": "Volume IOPS Read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "vol_iops_read{vol_name=~\"$volume_name\"}",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Volume IOPS Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "vol_iops_write{vol_name=~\"$volume_name\"}",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Physical Capacity Free (TB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cap_total{} - cap_used{}) / 1099511627776"
    }
   ]
  },
  {
   "title": "Volume Bandwidth Read (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "vol_bandwith_read{vol_name=~\"$volume_name\"} /1048576",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Volume Bandwidth Write(MBps)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 20 },
   "targets": [
    {
     "expr": "vol_bandwidth_write{vol_name=~\"$volume_name\"} /1048576",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Volume Latency Read (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "vol_latency_read{vol_name=~\"$volume_name\"} / 1000",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Volume Latency Write(ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 26 },
   "targets": [
    {
     "expr": "vol_latency_write{vol_name=~\"$volume_name\"} / 1000",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Volume IO Size Read (KB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "vol_iosize_read{vol_name=~\"$volume_name\"} /1024",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Volume IO Size Write (KB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 32 },
   "targets": [
    {
     "expr": "vol_iosize_write{vol_name=~\"$volume_name\"} /1024",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Queue Depth Read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "round(vol_latency_read{vol_name=~\"$volume_name\"} * vol_iops_read{vol_name=~\"$volume_name\"} /1000)",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Queue Depth Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 38 },
   "targets": [
    {
     "expr": "round(vol_latency_write{vol_name=~\"$volume_name\"} * vol_iops_write{vol_name=~\"$volume_name\"} /1000)",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 20, "x": 0, "y": 44 }, "options": { "content": "# Port Level Metrics" } },
  {
   "title": "FC port IOPS  Read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "fc_iops_read{fc_name=~\"$fc_port_name\"}",
     "legendFormat": "{{fc_name}}"
    }
   ]
  },
  {
   "title": "FC port IOPS  Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 46 },
   "targets": [
    {
     "expr": "fc_iops_write{fc_name=~\"$fc_port_name\"}",
     "legendFormat": "{{fc_name}}"
    }
   ]
  },
  {
   "title": "FC port Bandwidth Read (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "fc_bandwitdh_read{fc_name=~\"$fc_port_name\"} / 1048576",
     "legendFormat": "{{fc_name}}"
    }
   ]
  },
  {
   "title": "FC port Bandwidth Write(MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 52 },
   "targets": [
    {
     "expr": "fc_bandwidth_write{fc_name=~\"$fc_port_name\"} / 1048576",
     "legendFormat": "{{fc_name}}"
    }
   ]
  },
  {
   "title": "Ethernet port Bandwidth Read (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "eth_bandwitdh_read{eth_name=~\"$eth_port_name\"} / 1048576",
     "legendFormat": "{{eth_name}}"
    }
   ]
  },
  {
   "title": "Ethernet port Bandwidth Write (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 58 },
   "targets": [
    {
     "expr": "eth_bandwidth_write{eth_name=~\"$eth_port_name\"} /1048576",
     "legendFormat": "{{eth_name}}"
    }
   ]
  }
 ]
}